"""empty message

Revision ID: 2f7153358ba2
Revises: 846315245b2d
Create Date: 2016-12-15 13:01:00.922651

"""

# revision identifiers, used by Alembic.
revision = '2f7153358ba2'
down_revision = '846315245b2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_time', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timelines')
    ### end Alembic commands ###
