"""empty message

Revision ID: 846315245b2d
Revises: 8af392e02ddd
Create Date: 2016-12-15 12:48:46.093593

"""

# revision identifiers, used by Alembic.
revision = '846315245b2d'
down_revision = '8af392e02ddd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('created_time', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('created_time', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_time')
    op.drop_column('topics', 'created_time')
    ### end Alembic commands ###
