"""empty message

Revision ID: 8af392e02ddd
Revises: a16eb17f7f3f
Create Date: 2016-12-15 12:38:14.345285

"""

# revision identifiers, used by Alembic.
revision = '8af392e02ddd'
down_revision = 'a16eb17f7f3f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('created_time', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'created_time')
    ### end Alembic commands ###
