"""empty message

Revision ID: a16eb17f7f3f
Revises: 3557b93aa949
Create Date: 2016-12-15 12:30:06.242216

"""

# revision identifiers, used by Alembic.
revision = 'a16eb17f7f3f'
down_revision = '3557b93aa949'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_time', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'created_time')
    ### end Alembic commands ###
