"""empty message

Revision ID: a316e5b0a5d6
Revises: 2f7153358ba2
Create Date: 2017-01-12 20:59:43.174858

"""

# revision identifiers, used by Alembic.
revision = 'a316e5b0a5d6'
down_revision = '2f7153358ba2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('email', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('website', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'website')
    op.drop_column('users', 'email')
    op.drop_column('users', 'company')
    ### end Alembic commands ###
